package com.rl.expensewise.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006D43)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF59D193)
val onPrimaryContainerLight = Color(0xFF005735)
val secondaryLight = Color(0xFF3D674E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBCEBCB)
val onSecondaryContainerLight = Color(0xFF416B52)
val tertiaryLight = Color(0xFF0E629B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF81C1FF)
val onTertiaryContainerLight = Color(0xFF004F7F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF3)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF5FBF3)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFD8E6DA)
val onSurfaceVariantLight = Color(0xFF3D4A41)
val outlineLight = Color(0xFF6D7A70)
val outlineVariantLight = Color(0xFFBCCABE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322D)
val inverseOnSurfaceLight = Color(0xFFECF2EB)
val inversePrimaryLight = Color(0xFF65DD9D)
val surfaceDimLight = Color(0xFFD5DCD4)
val surfaceBrightLight = Color(0xFFF5FBF3)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5EE)
val surfaceContainerLight = Color(0xFFE9F0E8)
val surfaceContainerHighLight = Color(0xFFE3EAE2)
val surfaceContainerHighestLight = Color(0xFFDEE4DD)



val primaryDark = Color(0xFF77EEAD)
val onPrimaryDark = Color(0xFF003921)
val primaryContainerDark = Color(0xFF59D193)
val onPrimaryContainerDark = Color(0xFF005735)
val secondaryDark = Color(0xFFA3D1B3)
val onSecondaryDark = Color(0xFF0B3822)
val secondaryContainerDark = Color(0xFF254F38)
val onSecondaryContainerDark = Color(0xFF92BFA2)
val tertiaryDark = Color(0xFFBADBFF)
val onTertiaryDark = Color(0xFF003354)
val tertiaryContainerDark = Color(0xFF81C1FF)
val onTertiaryContainerDark = Color(0xFF004F7F)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDEE4DD)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDEE4DD)
val surfaceVariantDark = Color(0xFF3D4A41)
val onSurfaceVariantDark = Color(0xFFBCCABE)
val outlineDark = Color(0xFF879489)
val outlineVariantDark = Color(0xFF3D4A41)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DD)
val inverseOnSurfaceDark = Color(0xFF2C322D)
val inversePrimaryDark = Color(0xFF006D43)
val surfaceDimDark = Color(0xFF0F1511)
val surfaceBrightDark = Color(0xFF343B36)
val surfaceContainerLowestDark = Color(0xFF09100C)
val surfaceContainerLowDark = Color(0xFF171D19)
val surfaceContainerDark = Color(0xFF1B211D)
val surfaceContainerHighDark = Color(0xFF252B27)
val surfaceContainerHighestDark = Color(0xFF303631)
